image: node:lts
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - .next/cache
    - src/graphql/sdk.ts

stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  script:
    - yarn
    - yarn codegen
  only:
    - merge_requests
    - master

test:
  stage: test
  script: yarn jest --coverage
  only:
    - merge_requests

deploy:
  stage: deploy
  script: yarn now --token $NOW_DEPLOY_TOKEN --confirm
  only:
    - merge_requests

production:
  stage: deploy
  script: yarn now --token $NOW_DEPLOY_TOKEN --confirm --prod
  only:
    - master
