name: CI
on: [pull_request]
jobs:
  test:
    name: 'Lighthouse'
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for 200 from the Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@master
      id: waitFor200
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 60
    # access preview url
    - run: echo ${{ steps.waitFor200.outputs.url }}

    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts

    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
        urls: '${{ steps.waitFor200.outputs.url }}'

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
